name: Publish Slate Docs

on:
  push:
    branches: 
      - master
    paths:
    - 'src/docs/**'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build Slate Docs
      run: |
          cd src/docs
          gem install bundler
          bundle install --retry 3
          bundle exec middleman build --clean
    - name: Publish to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: src/docs/build
